# Generated by Django 4.2 on 2023-05-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(default=18, max_length=60)),
                ('GPA', models.FloatField(default=0.0, max_length=10)),
            ],
        ),
    ]
